# Do not edit this file.

import json
import re
from dotmap import DotMap


def to_json(x, filepath):
    with open(filepath, 'w') as fp:
        json.dump(x, fp)


def from_json(filepath):
    with open(filepath, 'r') as fp:
        data = json.load(fp)
    return data


def load_config(config_path):
    return DotMap(from_json(config_path))


def tokenize(text: str):
    # Remove non-alphanumeric characters and split into words
    words = re.findall(r'\w+', text.lower())
    return words
